### ISSUE TITLE
纠正一下

### ISSUE THREAD

**Issue by uninput** [ZYYO666/homepage#2]
纠正一下，原作者是https://github.com/ddiu8081

**Comment by ZYYO666** [comment]
嗯嗯,这个我知道的,忘记备注了,xhofe也是借鉴了ddiu,他们两款我都看过,也都开源了我是在他们的风格上进行自我发挥创作

**Comment by uninput** [comment]
可不可以帮我把这个issue删了，我有强迫症😢
