### ISSUE TITLE
本地运行无法引入CSS文件

### ISSUE THREAD

**Issue by xxynet** [ZYYO666/homepage#4]
Failed to load resource: net::ERR_FILE_NOT_FOUND
控制台显示访问资源的地址为file:///C:/static/css/style.css?v=1.33
在服务器上运行正常

**Comment by ZYYO666** [comment]
可能是因为路径,你再css和js路径前面加个./试试

**Comment by ywg2244** [comment]
因为作者用的是服务器环境，项目资源引用地址使用"/"绝对路径进行拼接资源，在服务器上默认找到域名进行隐式拼接，当然你本地有node环境的话 在该项目跟路径下使用"npx serve"自动启动一个本地环境可以运行，然而当然你也可使用作者说的方式，加上"./"使用

**Comment by ZYYO666** [comment]
嗯啊，好多人反映，我最近比较忙，明天改一下

**Comment by xxynet** [comment]
> 可能是因为路径,你再css和js路径前面加个./试试

感谢，我已经改好了，现在本地运行正常

**Comment by xxynet** [comment]
问题已解决
